[package]
name = "html-to-kotlin"
version = "0.0.0"
authors = ["Jonathan Cornaz"]
edition = "2021"
repository = "https://github.com/jcornaz/html-to-kotlin"

[dependencies]
tl = "0.7.7"
main_error = "0.1.2"

[dev-dependencies]
