[package]
name = "html-to-kotlin"
version = "0.0.0"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.72"
repository = "https://github.com/jcornaz/html-to-kotlin"

[dependencies]

[dev-dependencies]
